/* Violet Server Database Create Tables SQL */
/* for MySQL(MariaDB) */

CREATE TABLE `viewtotal` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`ArticleId` INT(11) NULL DEFAULT NULL,
	`TimeStamp` TIMESTAMP NULL DEFAULT NULL,
	`UserAppId` CHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `AritcleId` (`ArticleId`) USING BTREE,
	FULLTEXT INDEX `UserAppId` (`UserAppId`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `viewtime` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`ArticleId` INT(11) NULL DEFAULT NULL,
	`TimeStamp` TIMESTAMP NULL DEFAULT NULL,
	`ViewSeconds` INT(11) NULL DEFAULT NULL,
	`UserAppId` CHAR(50) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `AritcleId` (`ArticleId`) USING BTREE,
	FULLTEXT INDEX `UserAppId` (`UserAppId`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `article` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`TimeStamp` TIMESTAMP NULL DEFAULT NULL,
	`User` INT(11) NOT NULL,
	`Comments` INT(10) UNSIGNED ZEROFILL NOT NULL,
	`Title` CHAR(50) NULL DEFAULT '' COLLATE 'utf8_general_ci',
	`Body` VARCHAR(5000) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`Etc` VARCHAR(5000) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	`Board` INT(11) NOT NULL,
	`View` INT(11) NOT NULL DEFAULT 0,
	`UpVote` INT(11) NOT NULL DEFAULT 0,
	`DownVote` INT(11) NOT NULL DEFAULT 0,
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `Board` (`Board`) USING BTREE,
	CONSTRAINT `Board` FOREIGN KEY (`Board`) REFERENCES `violet`.`board` (`Id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `User` FOREIGN KEY (`User`) REFERENCES `violet`.`user` (`Pid`) ON UPDATE RESTRICT ON DELETE RESTRICT
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `voterecord` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`TimeStamp` TIMESTAMP NULL DEFAULT NULL,
	`Article`  INT(11) NOT NULL,
	/* 0: up, 1: down */
	`Status` INT(11) NOT NULL DEFAULT 0,
	PRIMARY KEY (`Id`) USING BTREE,
	CONSTRAINT `VoteReffer` FOREIGN KEY (`Article`) REFERENCES `violet`.`article` (`Id`) ON UPDATE RESTRICT ON DELETE RESTRICT
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `board` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`ShortName` CHAR(50) NOT NULL COLLATE 'utf8_general_ci',
	`Name` VARCHAR(50) NOT NULL COLLATE 'utf8_general_ci',
	`Description` VARCHAR(500) NULL DEFAULT NULL COLLATE 'utf8_general_ci',
	PRIMARY KEY (`Id`) USING BTREE,
	FULLTEXT INDEX `ShortName` (`ShortName`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `comment` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`ArticleId` INT(11) NOT NULL,
	`User` INT(11) NOT NULL,
	`TimeStamp` TIMESTAMP NULL DEFAULT NULL,
	`Body` VARCHAR(500) NULL DEFAULT '' COLLATE 'utf8_general_ci',
	PRIMARY KEY (`Id`) USING BTREE,
	INDEX `ArticleId` (`ArticleId`) USING BTREE,
	CONSTRAINT `ArticleId` FOREIGN KEY (`ArticleId`) REFERENCES `violet`.`article` (`Id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	CONSTRAINT `UserId` FOREIGN KEY (`User`) REFERENCES `violet`.`user` (`Pid`) ON UPDATE RESTRICT ON DELETE RESTRICT
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `user` (
	`Pid` INT(11) NOT NULL AUTO_INCREMENT,
	`Id` VARCHAR(50) NOT NULL COLLATE 'utf8_general_ci',
	`Password` VARCHAR(150) NOT NULL COLLATE 'utf8_general_ci',
	`UserAppId` VARCHAR(150) NOT NULL COLLATE 'utf8_general_ci',
	`NickName` VARCHAR(50) NOT NULL COLLATE 'utf8_general_ci',
	`Etc` VARCHAR(150) NOT NULL COLLATE 'utf8_general_ci',
	PRIMARY KEY (`Pid`) USING BTREE,
	FULLTEXT INDEX `Id` (`Id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `loginrecord` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`UserId` VARCHAR(50) NOT NULL COLLATE 'utf8_general_ci',
	`Password` VARCHAR(150) NOT NULL COLLATE 'utf8_general_ci',
	`TimeStamp` TIMESTAMP NULL DEFAULT NULL,
	`Status` INT(11) NOT NULL,
	PRIMARY KEY (`Id`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;